"use client";

import { useMemo, useState } from "react";
import { signOut } from "next-auth/react";
import { ArrowLeft, BookOpen, Check, ChevronLeft, ChevronRight, CircleUserRound, Feather, Heart, Image as ImageIcon, LogOut, Mail, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings, Sparkles, UserPlus, Users, X } from "lucide-react";

type Tab = "book" | "gallery" | "friends" | "me";
type Story = { id: number; date: string; day: string; title: string; excerpt: string; content: string; image: string; tone: string; people: string[]; public: boolean };
const stories: Story[] = [
  { id: 1, date: "2024 / 06 / 14", day: "FRI", title: "雨停在便利店门口", excerpt: "本来只是买一瓶水，最后和一只猫聊了十分钟。", content: "雨在便利店的玻璃门上写字。\n\n我们都没有急着走，店里的白灯把每个人的影子留在地面。橘猫从纸箱里探出头，像在确认今天是不是值得继续。\n\n后来雨停了，我们把伞借给了没有伞的人。", image: "https://images.unsplash.com/photo-1514897575457-c4db467cf78e?auto=format&fit=crop&w=900&q=80", tone: "ochre", people: ["你", "Mia"], public: true },
  { id: 2, date: "2024 / 05 / 28", day: "TUE", title: "错过末班车之后", excerpt: "城市把我们留在了同一个站台，刚刚好。", content: "末班车开走之后，站台突然变得很安静。\n\n我们交换了耳机里正在听的歌，也交换了一个不太成熟的计划：走回去，顺便看看凌晨的城市。", image: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=80", tone: "clay", people: ["你", "Noah", "June"], public: true },
  { id: 3, date: "2024 / 05 / 03", day: "FRI", title: "周五的面包店", excerpt: "烤箱响了一声，整个下午有了形状。", content: "我们在周五下午排队买面包。\n\n有人把最后一只可颂让给了身后的小朋友，老板多送了一块曲奇。好事情有时候就是这样，安静地挨在一起。", image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80", tone: "sand", people: ["你", "Kai"], public: false },
];
const gallery = stories.filter((story) => story.public);

function Brand() { return <div className="brand-mark"><span className="brand-icon">语</span><span><b>物语了</b><small>WuyuLe</small></span></div>; }
function NavItem({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span></button>; }

export default function Home() {
  const [tab, setTab] = useState<Tab>("book"); const [reader, setReader] = useState<Story | null>(null); const [page, setPage] = useState(0); const [showAdd, setShowAdd] = useState(false); const [commentStory, setCommentStory] = useState<number | null>(null); const [notice, setNotice] = useState("");
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); }; const openReader = (story: Story) => { setReader(story); setPage(0); };
  const contentPages = useMemo(() => reader ? [reader.content.split("\n\n")[0], reader.content.split("\n\n").slice(1).join("\n\n")] : [], [reader]);
  if (reader) return <main className="reader-screen"><header className="reader-header"><button className="icon-button" onClick={() => setReader(null)} aria-label="Back"><ArrowLeft size={20}/></button><span>READING · {reader.date}</span><button className="icon-button" onClick={() => notify("已收藏到你的书签")} aria-label="Bookmark"><Heart size={19}/></button></header><div className="reader-progress"><span style={{ width: `${(page + 1) * 50}%` }}/></div><article className="page-sheet" key={`${reader.id}-${page}`}><p className="eyebrow">{reader.day} · {reader.date}</p>{page === 0 ? <><h1>{reader.title}</h1><p className="lead">{reader.excerpt}</p><img src={reader.image} alt="" className="reader-image"/></> : <div className="reader-copy">{contentPages[1].split("\n").map((line, index) => line ? <p key={index}>{line}</p> : null)}</div>}<div className="page-number">0{page + 1} / 02</div></article><div className="reader-controls"><button disabled={page === 0} onClick={() => setPage(0)}><ChevronLeft size={18}/> PREV</button><span>SWIPE TO TURN</span><button disabled={page === 1} onClick={() => setPage(1)}>NEXT <ChevronRight size={18}/></button></div></main>;
  return <main className="app-shell"><header className="topbar"><Brand/><div className="top-actions"><button className="round-action" aria-label="Search" onClick={() => notify("搜索功能即将开放")}><Search size={18}/></button><button className="avatar" onClick={() => setTab("me")} aria-label="Profile">L</button></div></header><div className="content-area">{tab === "book" && <BookView onOpen={openReader}/>} {tab === "gallery" && <GalleryView onOpen={openReader} commentStory={commentStory} setCommentStory={setCommentStory} notify={notify}/>} {tab === "friends" && <FriendsView notify={notify}/>} {tab === "me" && <MeView notify={notify}/>}</div><nav className="bottom-nav"><NavItem active={tab === "book"} icon={<BookOpen size={20}/>} label="BOOK" onClick={() => setTab("book")}/><NavItem active={tab === "gallery"} icon={<ImageIcon size={20}/>} label="GALLERY" onClick={() => setTab("gallery")}/><button className="add-button" onClick={() => setShowAdd(true)} aria-label="Add story"><Plus size={26}/></button><NavItem active={tab === "friends"} icon={<Users size={20}/>} label="FRIENDS" onClick={() => setTab("friends")}/><NavItem active={tab === "me"} icon={<CircleUserRound size={20}/>} label="ME" onClick={() => setTab("me")}/></nav>{showAdd && <AddStory onClose={() => setShowAdd(false)} notify={notify}/>} {notice && <div className="toast"><Check size={16}/> {notice}</div>}</main>;
}

function BookView({ onOpen }: { onOpen: (story: Story) => void }) { return <section className="view"><div className="view-heading"><div><p className="eyebrow">YOUR ARCHIVE · 2024</p><h1>Book</h1></div><button className="text-button">FILTER <MoreHorizontal size={17}/></button></div><p className="intro">把那些差点无语的日子，写成以后会笑的故事。</p><div className="timeline">{stories.map((story, index) => <div className="timeline-row" key={story.id}><div className="date-rail"><strong>{story.date.split(" / ").slice(1).join("/")}</strong><span>{story.day}</span>{index !== stories.length - 1 && <i/>}</div><button className={`story-card ${story.tone}`} onClick={() => onOpen(story)}><div className="card-copy"><span className="card-kicker">EVENT {String(story.id).padStart(2, "0")} · {story.public ? "PUBLIC" : "PRIVATE"}</span><h2>{story.title}</h2><p>{story.excerpt}</p><span className="read-link">OPEN STORY <ChevronRight size={15}/></span></div><img src={story.image} alt=""/></button></div>)}</div></section>; }
function GalleryView({ onOpen, commentStory, setCommentStory, notify }: { onOpen: (story: Story) => void; commentStory: number | null; setCommentStory: (id: number | null) => void; notify: (message: string) => void }) { return <section className="view"><div className="view-heading"><div><p className="eyebrow">FROM YOUR CIRCLE</p><h1>Gallery</h1></div><button className="text-button" onClick={() => notify("已显示全部 Public 故事")}>PUBLIC <Sparkles size={15}/></button></div><div className="masonry">{gallery.map((story, index) => <article className={`gallery-card ${index % 2 ? "offset" : ""}`} key={story.id}><button className="image-button" onClick={() => onOpen(story)}><img src={story.image} alt={story.title}/></button><div className="gallery-meta"><p className="card-kicker">{story.date} · {story.people.join(" + ")}</p><h2>{story.title}</h2><p>{story.excerpt}</p><div className="comment-row"><button onClick={() => notify("已收藏这则故事")}><Heart size={15}/> 12</button><button onClick={() => setCommentStory(commentStory === story.id ? null : story.id)}><MessageCircle size={15}/> {commentStory === story.id ? "Hide" : "3"}</button></div>{commentStory === story.id && <div className="comments"><p><b>Mia</b> 这也太像我们了。</p><p><b>Noah</b> 留在站台的那晚很特别。</p><div className="comment-input"><input placeholder="写一句回应…"/><button aria-label="Send" onClick={() => notify("评论已加入（演示）")}><Send size={14}/></button></div></div>}</div></article>)}</div></section>; }
function FriendsView({ notify }: { notify: (message: string) => void }) { const [query, setQuery] = useState(""); const people = [{ name: "Mia Chen", handle: "@mia", status: "3 shared stories", initials: "MC" }, { name: "Noah Lin", handle: "@noah", status: "Last seen today", initials: "NL" }, { name: "June Wang", handle: "@june", status: "1 shared story", initials: "JW" }]; return <section className="view"><div className="view-heading"><div><p className="eyebrow">YOUR PEOPLE</p><h1>Friends</h1></div><button className="add-friend" onClick={() => notify("邀请链接已复制")}><UserPlus size={17}/> ADD</button></div><div className="search-field"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search email or username"/></div><div className="friend-list">{people.filter(p => `${p.name} ${p.handle}`.toLowerCase().includes(query.toLowerCase())).map(person => <div className="friend-row" key={person.handle}><span className="person-avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{person.handle} · {person.status}</small></div><button className="quiet-button" onClick={() => notify(`已打开 ${person.name} 的共享故事`)}>VIEW</button></div>)}</div><div className="invite-card"><Feather size={19}/><div><b>Share the little things</b><p>邀请朋友一起记录，事件会出现在双方的 Book。</p></div><button onClick={() => notify("邀请链接已复制")}>INVITE <ChevronRight size={15}/></button></div></section>; }
function MeView({ notify }: { notify: (message: string) => void }) { return <section className="view me-view"><div className="view-heading"><div><p className="eyebrow">YOUR CORNER</p><h1>Me</h1></div><button className="icon-button" onClick={() => notify("设置功能即将开放")}><Settings size={19}/></button></div><div className="profile-card"><span className="profile-avatar">L</span><div><h2>Laura Hanjing</h2><p>@laura · since 2024</p></div><button className="quiet-button" onClick={() => notify("资料编辑功能即将开放")}>EDIT</button></div><div className="stats"><div><strong>03</strong><span>STORIES</span></div><div><strong>02</strong><span>PUBLIC</span></div><div><strong>04</strong><span>FRIENDS</span></div></div><div className="settings-list"><button onClick={() => notify("邮箱已验证")}><Mail size={18}/><span>Email verification<small>laura@example.com · verified</small></span><Check size={17}/></button><button onClick={() => signOut({ callbackUrl: "/login" })}><LogOut size={18}/><span>Sign out<small>See you soon</small></span><ChevronRight size={17}/></button></div></section>; }
function AddStory({ onClose, notify }: { onClose: () => void; notify: (message: string) => void }) { const [visibility, setVisibility] = useState("PRIVATE"); return <div className="modal-backdrop" onClick={onClose}><section className="add-sheet" onClick={e => e.stopPropagation()}><div className="sheet-head"><div><p className="eyebrow">NEW MEMORY</p><h2>Add a story</h2></div><button className="icon-button" onClick={onClose}><X size={20}/></button></div><form onSubmit={e => { e.preventDefault(); onClose(); notify("故事已保存到 Book"); }}><label>TIME<input type="date" defaultValue="2024-06-14" required/></label><label>EVENT<input placeholder="Give it a title" required/></label><label>CONTENT<textarea rows={5} placeholder="What happened?" required/></label><label>PHOTOS<span className="upload-box"><ImageIcon size={19}/> Add photos <small>JPG, PNG · optional</small><input type="file" accept="image/*" multiple/></span></label><div className="visibility"><span>VISIBILITY</span><div><button type="button" className={visibility === "PRIVATE" ? "selected" : ""} onClick={() => setVisibility("PRIVATE")}>PRIVATE<small>Participants only</small></button><button type="button" className={visibility === "PUBLIC" ? "selected" : ""} onClick={() => setVisibility("PUBLIC")}>PUBLIC<small>Show in Gallery</small></button></div></div><button className="primary-button" type="submit">SAVE STORY <Check size={17}/></button></form></section></div>; }
